sudo: required
dist: trusty
language: java
addons:
    apt:
        packages:
        - expect
        - nmap
before_install:
   - pwd
install:
  - sudo make exInstall
  - sudo ./tmp/eXist-run.sh
script:
  - prove -v - < t/travis.txt
