sudo: required
dist: trusty
language: java
addons:
    apt:
        packages:
        - expect
        - nmap
        - tidy
before_install:
   - pwd
   - which expect
   - which prove
install:
  - sudo make --jobs=1 build
  - sudo ./tmp/eXist-run.sh
script:
  - prove -v - < t/travis.txt
