#!/usr/bin/env bash
source <( sed 's/=/="/g' config | sed -r 's/$/"/g' )
REPO="$(echo ${DEPLOY} | cut -d/ -f2 )"
OWNER="$(echo ${DEPLOY} | cut -d/ -f1 )"
EXIST_HOME='/usr/local/eXist'
P=admin
if [ -e ${ACCESS_TOKEN_PATH} ] ;then P="$(<${ACCESS_TOKEN_PATH})";fi

cmdClient="java -jar ${EXIST_HOME}/start.jar client -sqx -u admin -P ${P}"

TEST_MORE_PATH='bin/test-more-bash'
BASHLIB="$(
 find $TEST_MORE_PATH -type d |
 grep -E '/(bin|lib)$' |
 xargs -n1 printf "%s:")"

PATH="$BASHLIB$PATH"

source bash+ :std
